### ISSUE TITLE
Getting in contact

### ISSUE THREAD

**Issue by Jeopardy1011** [araynimax/phoskin#4]
hey I was just wondering if i could get in contact about a bit of a problem with the inspect api working with phoskins, sent you a dm on twitter by praayy if you got discord Pray#1391 if you could dm me back at all that would be awesome.

**Comment by araynimax** [comment]
Your problem will be related to  
https://github.com/araynimax/phoskin/issues/3

This problem is caused by a new rate limit by Valve and csgofloat blocked automatic requests to their API to compensate for that. The only known workaround is that you have to host the csgofloat API yourself. I can **not** assist you with that since I didn't develop the API.
The release of phoskin 1.2.1 has a new cvar called "pho_inspect_url" to switch the API endpoint to your self-hosted version of csgofloat. 
Read more in the linked issue and the "important" section in the latest version of the readme.md

If you have any issue directly related to phoskin feel free to open a new issue in which you please fully describe your problem, give a step-by-step guide to reproduce your problem and if relevant add your server logs.
